"""Initial migration.

Revision ID: 90dff70c4687
Revises: 
Create Date: 2022-12-06 17:39:47.895842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90dff70c4687'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.Enum('Action', 'Adventure', 'Animated', 'Biography', 'Comedy', 'Crime', 'Dance', 'Disaster', 'Documentary', 'Drama', 'Erotic', 'Family', 'Fantasy', 'FoundFootage', 'Historical', 'Horror', 'Independent', 'Legal', 'LiveAction', 'MartialArts', 'Musical', 'Mystery', 'Noir', 'Performance', 'Political', 'Romance', 'Satire', 'ScienceFiction', 'Short', 'Silent', 'Slasher', 'Sports', 'Spy', 'Superhero', 'Supernatural', 'Suspense', 'Teen', 'Thriller', 'War', 'Western', name='moviegenreenum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
